### Register as an admin
POST http://localhost:8080/api/v1/identity/register/admin
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "password",
  "firstName": "John",
  "lastName": "Doe"
}

### Login as an admin
POST http://localhost:8080/api/v1/identity/login/admin
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "password"
}

### Create an office user
POST http://tenant1.localhost:8080/api/v1/identity/register/office
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYWRtaW4iLCJzdWIiOiI2NTA5ZjI0YzBiNDU1YjZmNWIyZTM2NWMiLCJpYXQiOjE2OTUyODkzMDAsImV4cCI6MTY5NTI5MDc0MH0.816H_lD-ZuFuxWZ_rWomF9zAtDvgGD-2CjokBm-Qxi8

{
  "email": "johndoe@example.com",
  "firstName": "John",
  "lastName": "Doe"
}

### Login as an office user
POST http://tenant1.localhost:8080/api/v1/identity/login/office
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "qjo6sFzkAD"
}

### Create a teacher user
POST http://tenant1.localhost:8080/api/v1/identity/register/teacher
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoib2ZmaWNlIiwidGVuYW50SWQiOnsidGltZXN0YW1wIjoxNjk1MTUzNjg0LCJkYXRlIjoxNjk1MTUzNjg0MDAwfSwic3ViIjoiNjUwYzExNTZlNGQzNDU0ZDc3ODRkM2E2IiwiaWF0IjoxNjk1MjkxMDMxLCJleHAiOjE2OTUyOTI0NzF9.axKAWfXWbzLQoLXPQ0uTgGfcq9dySQc-XoSGuIAtqF8

{
  "email": "johndoe@example.com",
  "firstName": "John",
  "lastName": "Doe"
}