### Create a tenant
POST http://localhost:8080/api/v1/tenants
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "tenant1",
  "slug": "tenant1"
}

### List tenants owned by current user
GET http://localhost:8080/api/v1/tenants
Content-Type: application/json
Authorization: Bearer {{adminToken}}