### Create a tenant
POST http://localhost:8080/api/v1/tenants
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYWRtaW4iLCJzdWIiOiI2NTA5ZjI0YzBiNDU1YjZmNWIyZTM2NWMiLCJpYXQiOjE2OTUxNTQyOTksImV4cCI6MTY5NTE1NTczOX0.lMvFSJ2C0i9Ro-hvZfP5L655pSm3z1uObIznS2DiAjg

{
  "name": "tenant1",
  "slug": "tenant1"
}
